import "./globals.css";
import { Inter } from "next/font/google";
import { NavBtn } from "@/components/buttons.js";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "JNT Cargo Kramat Jati",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} container mx-auto px-0 pt-16`}>
        <header className="flex justify-between items-center mb-4">
          <Link href="/">
            <>
              <Image
                src="/asset/jtcargo-logo-retina.png"
                alt="Vercel Logo"
                className="dark:invert"
                width={200}
                height={24}
                priority
              />
            </>
          </Link>
          <div>
            <NavBtn label="Layanan" url="/layanan"></NavBtn>
            <NavBtn label="Tentang Kami" url="/tentang-kami"></NavBtn>
            <NavBtn label="Kontak" url="/kontak"></NavBtn>
            <NavBtn label="Whatsapp" url="/wa"></NavBtn>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
